<?php 
$vt=array(
array('sehir_ID'=>'1','ad'=>'Adana','bolge_ad'=>'Akdeniz','bolge_ID'=>1),
array('sehir_ID'=>'2','ad'=>'Adıyaman','bolge_ad'=>'Güneydoğu Anadolu','bolge_ID'=>7),
array('sehir_ID'=>'3','ad'=>'Afyon','bolge_ad'=>'Ege','bolge_ID'=>2),
array('sehir_ID'=>'4','ad'=>'Ağrı','bolge_ad'=>'Doğu Anadolu','bolge_ID'=>6),
array('sehir_ID'=>'5','ad'=>'Amasya','bolge_ad'=>'Karadeniz','bolge_ID'=>4),
array('sehir_ID'=>'6','ad'=>'Ankara','bolge_ad'=>'İç Anadolu','bolge_ID'=>5),
array('sehir_ID'=>'7','ad'=>'Antalya','bolge_ad'=>'Akdeniz','bolge_ID'=>1),
array('sehir_ID'=>'8','ad'=>'Artvin','bolge_ad'=>'Karadeniz','bolge_ID'=>4),
array('sehir_ID'=>'9','ad'=>'Aydın','bolge_ad'=>'Ege','bolge_ID'=>2),
array('sehir_ID'=>'10','ad'=>'Balıkesir','bolge_ad'=>'Marmara','bolge_ID'=>3),
array('sehir_ID'=>'11','ad'=>'Bilecik','bolge_ad'=>'Marmara','bolge_ID'=>3),
array('sehir_ID'=>'12','ad'=>'Bingöl','bolge_ad'=>'Doğu Anadolu','bolge_ID'=>6),
array('sehir_ID'=>'13','ad'=>'Bitlis','bolge_ad'=>'Doğu Anadolu','bolge_ID'=>6),
array('sehir_ID'=>'14','ad'=>'Bolu','bolge_ad'=>'Karadeniz','bolge_ID'=>4),
array('sehir_ID'=>'15','ad'=>'Burdur','bolge_ad'=>'Akdeniz','bolge_ID'=>1),
array('sehir_ID'=>'16','ad'=>'Bursa','bolge_ad'=>'Marmara','bolge_ID'=>3),
array('sehir_ID'=>'17','ad'=>'Çanakkale','bolge_ad'=>'Marmara','bolge_ID'=>3),
array('sehir_ID'=>'18','ad'=>'Çankırı','bolge_ad'=>'İç Anadolu','bolge_ID'=>5),
array('sehir_ID'=>'19','ad'=>'Çorum','bolge_ad'=>'Karadeniz','bolge_ID'=>4),
array('sehir_ID'=>'20','ad'=>'Denizli','bolge_ad'=>'Ege','bolge_ID'=>2),
array('sehir_ID'=>'21','ad'=>'Diyarbakır','bolge_ad'=>'Güneydoğu Anadolu','bolge_ID'=>7),
array('sehir_ID'=>'22','ad'=>'Edirne','bolge_ad'=>'Karadeniz','bolge_ID'=>4),
array('sehir_ID'=>'23','ad'=>'Elazığ','bolge_ad'=>'Doğu Anadolu','bolge_ID'=>6),
array('sehir_ID'=>'24','ad'=>'Erzincan','bolge_ad'=>'Doğu Anadolu','bolge_ID'=>6),
array('sehir_ID'=>'25','ad'=>'Erzurum','bolge_ad'=>'Doğu Anadolu','bolge_ID'=>6),
array('sehir_ID'=>'26','ad'=>'Eskişehir','bolge_ad'=>'İç Anadolu','bolge_ID'=>5),
array('sehir_ID'=>'27','ad'=>'Gaziantep','bolge_ad'=>'Güneydoğu Anadolu','bolge_ID'=>7),
array('sehir_ID'=>'28','ad'=>'Giresun','bolge_ad'=>'Karadeniz','bolge_ID'=>4),
array('sehir_ID'=>'29','ad'=>'Gümüşhane','bolge_ad'=>'Karadeniz','bolge_ID'=>4),
array('sehir_ID'=>'30','ad'=>'Hakkari','bolge_ad'=>'Doğu Anadolu','bolge_ID'=>6),
array('sehir_ID'=>'31','ad'=>'Hatay','bolge_ad'=>'Akdeniz','bolge_ID'=>1),
array('sehir_ID'=>'32','ad'=>'Isparta','bolge_ad'=>'Akdeniz','bolge_ID'=>1),
array('sehir_ID'=>'33','ad'=>'Mersin','bolge_ad'=>'Akdeniz','bolge_ID'=>1),
array('sehir_ID'=>'34','ad'=>'İstanbul','bolge_ad'=>'Marmara','bolge_ID'=>3),
array('sehir_ID'=>'35','ad'=>'İzmir','bolge_ad'=>'Ege','bolge_ID'=>2),
array('sehir_ID'=>'36','ad'=>'Kars','bolge_ad'=>'Doğu Anadolu','bolge_ID'=>6),
array('sehir_ID'=>'37','ad'=>'Kastamonu','bolge_ad'=>'Karadeniz','bolge_ID'=>4),
array('sehir_ID'=>'38','ad'=>'Kayseri','bolge_ad'=>'İç Anadolu','bolge_ID'=>5),
array('sehir_ID'=>'39','ad'=>'Kırklareli','bolge_ad'=>'Marmara','bolge_ID'=>3),
array('sehir_ID'=>'40','ad'=>'Kırşehir','bolge_ad'=>'İç Anadolu','bolge_ID'=>5),
array('sehir_ID'=>'41','ad'=>'Kocaeli','bolge_ad'=>'Marmara','bolge_ID'=>3),
array('sehir_ID'=>'42','ad'=>'Konya','bolge_ad'=>'İç Anadolu','bolge_ID'=>5),
array('sehir_ID'=>'43','ad'=>'Kütahya','bolge_ad'=>'Ege','bolge_ID'=>2),
array('sehir_ID'=>'44','ad'=>'Malatya','bolge_ad'=>'Doğu Anadolu','bolge_ID'=>6),
array('sehir_ID'=>'45','ad'=>'Manisa','bolge_ad'=>'Ege','bolge_ID'=>2),
array('sehir_ID'=>'46','ad'=>'Kahramanmaraş','bolge_ad'=>'Akdeniz','bolge_ID'=>1),
array('sehir_ID'=>'47','ad'=>'Mardin','bolge_ad'=>'Güneydoğu Anadolu','bolge_ID'=>7),
array('sehir_ID'=>'48','ad'=>'Muğla','bolge_ad'=>'Ege','bolge_ID'=>2),
array('sehir_ID'=>'49','ad'=>'Muş','bolge_ad'=>'Doğu Anadolu','bolge_ID'=>6),
array('sehir_ID'=>'50','ad'=>'Nevşehir','bolge_ad'=>'İç Anadolu','bolge_ID'=>5),
array('sehir_ID'=>'51','ad'=>'Niğde','bolge_ad'=>'İç Anadolu','bolge_ID'=>5),
array('sehir_ID'=>'52','ad'=>'Ordu','bolge_ad'=>'Karadeniz','bolge_ID'=>4),
array('sehir_ID'=>'53','ad'=>'Rize','bolge_ad'=>'Karadeniz','bolge_ID'=>4),
array('sehir_ID'=>'54','ad'=>'Sakarya','bolge_ad'=>'Marmara','bolge_ID'=>3),
array('sehir_ID'=>'55','ad'=>'Samsun','bolge_ad'=>'Karadeniz','bolge_ID'=>4),
array('sehir_ID'=>'56','ad'=>'Siirt','bolge_ad'=>'Güneydoğu Anadolu','bolge_ID'=>7),
array('sehir_ID'=>'57','ad'=>'Sinop','bolge_ad'=>'Karadeniz','bolge_ID'=>4),
array('sehir_ID'=>'58','ad'=>'Sivas','bolge_ad'=>'İç Anadolu','bolge_ID'=>5),
array('sehir_ID'=>'59','ad'=>'Tekirdağ','bolge_ad'=>'Marmara','bolge_ID'=>3),
array('sehir_ID'=>'60','ad'=>'Tokat','bolge_ad'=>'Karadeniz','bolge_ID'=>4),
array('sehir_ID'=>'61','ad'=>'Trabzon','bolge_ad'=>'Karadeniz','bolge_ID'=>4),
array('sehir_ID'=>'62','ad'=>'Tunceli','bolge_ad'=>'Doğu Anadolu','bolge_ID'=>6),
array('sehir_ID'=>'63','ad'=>'Şanlıurfa','bolge_ad'=>'Güneydoğu Anadolu','bolge_ID'=>7),
array('sehir_ID'=>'64','ad'=>'Uşak','bolge_ad'=>'Ege','bolge_ID'=>2),
array('sehir_ID'=>'65','ad'=>'Van','bolge_ad'=>'Doğu Anadolu','bolge_ID'=>6),
array('sehir_ID'=>'66','ad'=>'Yozgat','bolge_ad'=>'İç Anadolu','bolge_ID'=>5),
array('sehir_ID'=>'67','ad'=>'Zonguldak','bolge_ad'=>'Karadeniz','bolge_ID'=>4),
array('sehir_ID'=>'68','ad'=>'Aksaray','bolge_ad'=>'İç Anadolu','bolge_ID'=>5),
array('sehir_ID'=>'69','ad'=>'Bayburt','bolge_ad'=>'Karadeniz','bolge_ID'=>4),
array('sehir_ID'=>'70','ad'=>'Karaman','bolge_ad'=>'İç Anadolu','bolge_ID'=>5),
array('sehir_ID'=>'71','ad'=>'Kırıkkale','bolge_ad'=>'İç Anadolu','bolge_ID'=>5),
array('sehir_ID'=>'72','ad'=>'Batman','bolge_ad'=>'Güneydoğu Anadolu','bolge_ID'=>7),
array('sehir_ID'=>'73','ad'=>'Şırnak','bolge_ad'=>'Güneydoğu Anadolu','bolge_ID'=>7),
array('sehir_ID'=>'74','ad'=>'Bartın','bolge_ad'=>'Karadeniz','bolge_ID'=>4),
array('sehir_ID'=>'75','ad'=>'Ardahan','bolge_ad'=>'Doğu Anadolu','bolge_ID'=>6),
array('sehir_ID'=>'76','ad'=>'Iğdır','bolge_ad'=>'Doğu Anadolu','bolge_ID'=>6),
array('sehir_ID'=>'77','ad'=>'Yalova','bolge_ad'=>'Marmara','bolge_ID'=>3),
array('sehir_ID'=>'78','ad'=>'Karabük','bolge_ad'=>'Karadeniz','bolge_ID'=>4),
array('sehir_ID'=>'79','ad'=>'Kilis','bolge_ad'=>'Güneydoğu Anadolu','bolge_ID'=>7),
array('sehir_ID'=>'80','ad'=>'Osmaniye','bolge_ad'=>'Akdeniz','bolge_ID'=>1),
array('sehir_ID'=>'81','ad'=>'Düzce','bolge_ad'=>'Karadeniz','bolge_ID'=>4)
);
//print_r($vt);
exit;
//veritabanına çoklu veri ekleme
$i=0;
foreach ($vt as $t => $tval) {
	$cg= $i++;
	z(2,$vt[$cg],'bolge');
}

?>